"""Variable definitions for forecasting decomposition."""

from __future__ import annotations

from enum import Enum
from typing import Any, Literal, Optional, Union

from pydantic import BaseModel, Field, ConfigDict, TypeAdapter, model_validator


class VariableType(str, Enum):
    """Type of variable in the forecasting model."""
    BINARY = "binary"           # Yes/No, True/False
    CONTINUOUS = "continuous"   # Real-valued
    DISCRETE = "discrete"       # Finite set of values
    ORDINAL = "ordinal"         # Ordered categories


class Variable(BaseModel):
    """A variable that may be relevant to a forecasting question.
    
    Variables are generated by the LLM as factors that could influence
    the answer to the main question.
    """
    model_config = ConfigDict(frozen=True)
    
    name: str = Field(..., description="Short identifier for the variable")
    description: str = Field(..., description="What this variable represents")
    # NOTE: the description feeds the JSON schema the LLM sees — only advertise
    # the types the elicitation pipeline accepts (VariableList validates
    # binary | continuous; a 'discrete' item would be dropped).
    type: VariableType = Field(VariableType.CONTINUOUS, description="Type: 'binary' or 'continuous'")

    def to_query_variable(self) -> str: 
        """Get a string representation suitable for queries."""
        return f"{self.name} ({self.description})"

class BinaryVariable(Variable):
    """A binary (yes/no) variable."""
    # Literal, not the open enum: otherwise a hallucinated type ('discrete')
    # validates as a pseudo-binary instead of being rejected by the union.
    type: Literal[VariableType.BINARY] = VariableType.BINARY

class ContinuousVariable(Variable):
    """A continuous (real-valued) variable."""

    type: Literal[VariableType.CONTINUOUS] = VariableType.CONTINUOUS
    
    # Domain bounds
    lower_bound: float = Field(0, description="Lower bound of domain")
    upper_bound: float = Field(0, description="Upper bound of domain")
    
    # Unit of measurement
    unit: Optional[str] = Field(None, description="Unit of measurement (e.g., 'people', 'USD')")
    
    def get_domain(self) -> tuple[float, float]:
        """Get the domain bounds."""
        return (self.lower_bound, self.upper_bound)
    
class DiscreteVariable(Variable):
    """A discrete variable with a finite set of possible values."""
    type: VariableType = VariableType.DISCRETE
    # Possible values
    categories: list[str] = Field(default_factory=list, description="List of possible values")

_VARIABLE_ITEM_ADAPTER = TypeAdapter(Union[BinaryVariable, ContinuousVariable])


class VariableList(BaseModel):
    """A list of variables."""
    model_config = ConfigDict(frozen=True)
    variables: list[Union[BinaryVariable, ContinuousVariable]] = Field(default_factory=list, description="List of variables")

    @model_validator(mode="before")
    @classmethod
    def _salvage_items(cls, data):
        """LLM-boundary leniency: validate items individually and drop the
        invalid ones (one hallucinated 'discrete' variable must not void the
        rest of the list). Raises only when nothing survives, so callers'
        retry logic still triggers on genuinely bad responses."""
        if not (isinstance(data, dict) and isinstance(data.get("variables"), list)):
            return data
        kept, dropped = [], []
        for item in data["variables"]:
            try:
                v = _VARIABLE_ITEM_ADAPTER.validate_python(item)
                if isinstance(v, ContinuousVariable) and \
                        not v.upper_bound > v.lower_bound:
                    # bounds default to (0, 0) when omitted — such a variable
                    # would be silently unusable downstream (solvers need a
                    # real domain); reject it HERE so the caller's retry can
                    # fix it while the LLM is still on the line
                    raise ValueError(
                        f"degenerate domain [{v.lower_bound}, {v.upper_bound}]"
                        " — continuous variables need lower_bound < upper_bound")
                kept.append(v)
            except Exception as e:
                name = item.get("name", "?") if isinstance(item, dict) else "?"
                dropped.append(f"{name}: {str(e).splitlines()[0][:120]}")
        if dropped:
            print(f"VariableList: dropped {len(dropped)} invalid variable(s): "
                  f"{'; '.join(dropped)}")
        if not kept and dropped:
            raise ValueError(f"no valid variables ({len(dropped)} dropped)")
        return {**data, "variables": kept}


