"""Variable definitions for forecasting decomposition."""

from __future__ import annotations

from enum import Enum
from typing import Any, Optional, Union

from pydantic import BaseModel, Field, ConfigDict


class VariableType(str, Enum):
    """Type of variable in the forecasting model."""
    BINARY = "binary"           # Yes/No, True/False
    CONTINUOUS = "continuous"   # Real-valued
    DISCRETE = "discrete"       # Finite set of values
    ORDINAL = "ordinal"         # Ordered categories


class Variable(BaseModel):
    """A variable that may be relevant to a forecasting question.
    
    Variables are generated by the LLM as factors that could influence
    the answer to the main question.
    """
    model_config = ConfigDict(frozen=True)
    
    name: str = Field(..., description="Short identifier for the variable")
    description: str = Field(..., description="What this variable represents")
    type: VariableType = Field(VariableType.CONTINUOUS, description="Type: binary, continuous, discrete, or ordinal")

    def to_query_variable(self) -> str: 
        """Get a string representation suitable for queries."""
        return f"{self.name}: {self.description}"

class BinaryVariable(Variable):
    """A binary (yes/no) variable."""
    type: VariableType = Field(VariableType.BINARY, frozen=True)

class ContinuousVariable(Variable):
    """A continuous (real-valued) variable."""
    
    type: VariableType = Field(VariableType.CONTINUOUS, frozen=True)
    
    # Domain bounds
    lower_bound: float = Field(0, description="Lower bound of domain")
    upper_bound: float = Field(0, description="Upper bound of domain")
    
    # Unit of measurement
    unit: Optional[str] = Field(None, description="Unit of measurement (e.g., 'people', 'USD')")
    
    def get_domain(self) -> tuple[float, float]:
        """Get the domain bounds."""
        return (self.lower_bound, self.upper_bound)
    
class DiscreteVariable(Variable):
    """A discrete variable with a finite set of possible values."""
    type: VariableType = Field(VariableType.DISCRETE, frozen=True)
    
    # Possible values
    categories: list[str] = Field(default_factory=list, description="List of possible values")

class VariableList(BaseModel):
    """A list of variables."""
    model_config = ConfigDict(frozen=True)
    
    variables: list[Union[BinaryVariable, ContinuousVariable]] = Field(default_factory=list, description="List of variables")

demo_continuous_var = ContinuousVariable(
    name="daily_high_temp",
    description="The daily high temperature in degrees Fahrenheit",
    lower_bound=30.0,
    upper_bound=100.0,
    unit="degrees F"
) 

demo_binary_var = BinaryVariable(
    name="is_raining",
    description="Whether it is currently raining"
)

